//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPS_web.NCBServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NCBServiceReference.INCB_Service")]
    public interface INCB_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INCB_Service/getPayment", ReplyAction="http://tempuri.org/INCB_Service/getPaymentResponse")]
        void getPayment(float amount, long cardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INCB_Service/getPayment", ReplyAction="http://tempuri.org/INCB_Service/getPaymentResponse")]
        System.Threading.Tasks.Task getPaymentAsync(float amount, long cardNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INCB_ServiceChannel : JPS_web.NCBServiceReference.INCB_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NCB_ServiceClient : System.ServiceModel.ClientBase<JPS_web.NCBServiceReference.INCB_Service>, JPS_web.NCBServiceReference.INCB_Service {
        
        public NCB_ServiceClient() {
        }
        
        public NCB_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NCB_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NCB_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NCB_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void getPayment(float amount, long cardNumber) {
            base.Channel.getPayment(amount, cardNumber);
        }
        
        public System.Threading.Tasks.Task getPaymentAsync(float amount, long cardNumber) {
            return base.Channel.getPaymentAsync(amount, cardNumber);
        }
    }
}
