<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Maintain.aspx.cs" Inherits="NCB_web.Admin.Maintain" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="container body-content">
        <h1>Maintain users and roles</h1>
        <style>
            .hiddencol {
                display: none;
            }
        </style>
        (Only users associated with the Admin role can access this page)   
    
    <div class="row">
        <div class="col-sm-12 table-responsive">
            <h2>Users</h2>

            <asp:GridView ID="GridView1" runat="server" DataKeyNames="CustomerID" AutoPostBack="True" OnRowDeleted="RowDeleted" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" AllowSorting="True" CssClass="table table-bordered table-striped table-condensed"
                OnPreRender="GridView_PreRender" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                <Columns>
                    <asp:BoundField DataField="CustomerID" HeaderStyle-CssClass="hiddencol" HeaderText="ID" ItemStyle-CssClass="hiddencol" SortExpression="CustomerID"></asp:BoundField>
                    <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName"></asp:BoundField>
                    <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName"></asp:BoundField>
                    <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email"></asp:BoundField>
                    <asp:BoundField DataField="Name" ReadOnly="true" HeaderText="Role" SortExpression="Name"></asp:BoundField>
                    <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address"></asp:BoundField>
                </Columns>
            </asp:GridView>

            <asp:SqlDataSource runat="server" ID="SqlDataSource1" ConnectionString='<%$ ConnectionStrings:DefaultConnection %>' SelectCommand="SELECT Customers.FirstName,Customers.CustomerID, Customers.LastName, Customers.Address, AspNetUsers.Email, AspNetRoles.Name FROM AspNetUsers INNER JOIN AspNetUserRoles ON AspNetUsers.Id = AspNetUserRoles.UserId INNER JOIN Customers ON Customers.CustomerID = AspNetUsers.Id INNER JOIN AspNetRoles ON AspNetUserRoles.RoleId = AspNetRoles.Id" UpdateCommand="UPDATE [Customers]
   SET [FirstName] = @FirstName,
       [LastName] = @LastName,
      [Address] = @Address
 WHERE [Customers].[CustomerID] = @CustomerID "
                DeleteCommand="Delete from Accounts WHERE CustomerCustomerID= @CustomerID;Delete from Customers WHERE CustomerID= @CustomerID;Delete from AspNetUsers WHERE Id= @CustomerID
                ;Delete from AspNetUserRoles WHERE UserId= @CustomerID"></asp:SqlDataSource>
        </div>
    </div>
        <div class="row">
            <h2>Add New User</h2>
            <asp:ValidationSummary runat="server" CssClass="text-danger" ValidationGroup="addValidation" />
            <div class="form-group">
                <asp:Label runat="server" AssociatedControlID="tbEmail" ValidationGroup="addValidation" CssClass="col-md-2 control-label">Email</asp:Label>
                <div class="col-md-10">
                    <asp:TextBox runat="server" ID="tbEmail" CssClass="form-control" ValidationGroup="addValidation" TextMode="Email" />
                    <asp:RequiredFieldValidator runat="server" ValidationGroup="addValidation" ControlToValidate="tbEmail"
                        CssClass="text-danger" ErrorMessage="The email field is required." />
                </div>
            </div>

            <div class="form-group">
                <asp:Label runat="server" AssociatedControlID="tbFname" CssClass="col-md-2 control-label">First Name</asp:Label>
                <div class="col-md-10">
                    <asp:TextBox runat="server" ID="tbFname" ValidationGroup="addValidation" CssClass="form-control" TextMode="SingleLine" />
                    <asp:RequiredFieldValidator runat="server" ValidationGroup="addValidation" ControlToValidate="tbFname"
                        CssClass="text-danger" ErrorMessage="First Name is required" />
                </div>
            </div>
            <div class="form-group">
                <asp:Label runat="server" AssociatedControlID="tbLName" CssClass="col-md-2 control-label">Last Name</asp:Label>
                <div class="col-md-10">
                    <asp:TextBox runat="server" ID="tbLName" CssClass="form-control" ValidationGroup="addValidation" TextMode="SingleLine" />
                    <asp:RequiredFieldValidator runat="server" ValidationGroup="addValidation" ControlToValidate="tbLName"
                        CssClass="text-danger" ErrorMessage="Last Name is required" />
                </div>
            </div>
            <div class="form-group">
                <asp:Label runat="server" AssociatedControlID="tbAddress" CssClass="col-md-2 control-label">Address</asp:Label>
                <div class="col-md-10">
                    <asp:TextBox runat="server" ID="tbAddress" CssClass="form-control" ValidationGroup="addValidation" TextMode="MultiLine" Width="280px" />
                    <asp:RequiredFieldValidator runat="server" ValidationGroup="addValidation" ControlToValidate="tbAddress"
                        CssClass="text-danger" ErrorMessage="Address is required" />
                </div>
            </div>
            <div class="form-group">
                <asp:Label runat="server" AssociatedControlID="ddlrrole" CssClass="col-md-2 control-label">Role</asp:Label>
                <div class="col-md-10">
                    <asp:DropDownList ID="ddlrrole" runat="server" ValidationGroup="addValidation" Width="280px" CssClass="form-control" DataSourceID="SqlDataSource2" DataTextField="Name" DataValueField="Name">
                        <asp:ListItem>Admin</asp:ListItem>
                        <asp:ListItem></asp:ListItem>
                    </asp:DropDownList>
                    <asp:SqlDataSource runat="server" ID="SqlDataSource2" ConnectionString='<%$ ConnectionStrings:DefaultConnection %>' SelectCommand="SELECT Name FROM AspNetRoles"></asp:SqlDataSource>
                    <asp:RequiredFieldValidator runat="server" ValidationGroup="addValidation" ControlToValidate="ddlrrole"
                        CssClass="text-danger" ErrorMessage="Role is required" />
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <asp:Button runat="server" OnClick="CreateUser_Click" ValidationGroup="addValidation" Text="Add New User" CssClass="btn btn-default" />
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-6">
                <h2>Roles</h2>
                <asp:GridView ID="grdRoles" runat="server" DataKeyNames="Id"
                    AutoGenerateColumns="false" SelectMethod="grdRoles_GetData"
                    CssClass="table table-bordered table-striped table-condensed"
                    OnPreRender="GridView_PreRender">
                    <Columns>
                        <asp:BoundField HeaderText="Role Name" DataField="Name" />
                        <asp:CommandField ShowSelectButton="true" />
                    </Columns>
                </asp:GridView>
                <asp:DetailsView ID="dvRoles" runat="server" DataKeyNames="Id"
                    AutoGenerateRows="false" CssClass="table table-bordered table-condensed"
                    SelectMethod="dvRoles_GetItem" UpdateMethod="dvRoles_UpdateItem"
                    InsertMethod="dvRoles_InsertItem" DeleteMethod="dvRoles_DeleteItem">
                    <Fields>
                        <asp:BoundField HeaderText="Role Name" DataField="Name" />
                        <asp:CommandField ShowEditButton="true" ShowInsertButton="true"
                            ShowDeleteButton="true" />
                    </Fields>
                </asp:DetailsView>
            </div>
            <div class="col-sm-6">
                <h2>Add Roles to User</h2>
                <div class="form-group">
                    <label class="control-label">Select a user:</label>
                    <asp:DropDownList ID="ddlUsers" runat="server"
                        SelectMethod="grdUsers_GetData" DataValueField="Id"
                        DataTextField="UserName" CssClass="form-control">
                    </asp:DropDownList>
                </div>
                <div class="form-group">
                    <label class="control-label">Add one or more roles:</label>
                    <asp:ListBox ID="lstRoles" runat="server" SelectionMode="Multiple"
                        SelectMethod="grdRoles_GetData" DataValueField="Id"
                        DataTextField="Name" CssClass="form-control"></asp:ListBox>
                </div>
                <div class="form-group">
                    <asp:Button ID="btnAddRoles" runat="server" UseSubmitBehavior="false" CausesValidation="false" Text="Add Roles"
                        CssClass="btn btn-default" OnClick="btnAddRoles_Click" />
                </div>
            </div>
        </div>

    </div>
</asp:Content>
