//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPS_web.BNS_ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BNS_ServiceReference.BNS_ServiceSoap")]
    public interface BNS_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name billID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPayment", ReplyAction="*")]
        JPS_web.BNS_ServiceReference.getPaymentResponse getPayment(JPS_web.BNS_ServiceReference.getPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<JPS_web.BNS_ServiceReference.getPaymentResponse> getPaymentAsync(JPS_web.BNS_ServiceReference.getPaymentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPayment", Namespace="http://tempuri.org/", Order=0)]
        public JPS_web.BNS_ServiceReference.getPaymentRequestBody Body;
        
        public getPaymentRequest() {
        }
        
        public getPaymentRequest(JPS_web.BNS_ServiceReference.getPaymentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPaymentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long cardNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string billID;
        
        public getPaymentRequestBody() {
        }
        
        public getPaymentRequestBody(float amount, long cardNumber, string billID) {
            this.amount = amount;
            this.cardNumber = cardNumber;
            this.billID = billID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPaymentResponse", Namespace="http://tempuri.org/", Order=0)]
        public JPS_web.BNS_ServiceReference.getPaymentResponseBody Body;
        
        public getPaymentResponse() {
        }
        
        public getPaymentResponse(JPS_web.BNS_ServiceReference.getPaymentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getPaymentResponseBody {
        
        public getPaymentResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BNS_ServiceSoapChannel : JPS_web.BNS_ServiceReference.BNS_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BNS_ServiceSoapClient : System.ServiceModel.ClientBase<JPS_web.BNS_ServiceReference.BNS_ServiceSoap>, JPS_web.BNS_ServiceReference.BNS_ServiceSoap {
        
        public BNS_ServiceSoapClient() {
        }
        
        public BNS_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BNS_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BNS_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BNS_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JPS_web.BNS_ServiceReference.getPaymentResponse JPS_web.BNS_ServiceReference.BNS_ServiceSoap.getPayment(JPS_web.BNS_ServiceReference.getPaymentRequest request) {
            return base.Channel.getPayment(request);
        }
        
        public void getPayment(float amount, long cardNumber, string billID) {
            JPS_web.BNS_ServiceReference.getPaymentRequest inValue = new JPS_web.BNS_ServiceReference.getPaymentRequest();
            inValue.Body = new JPS_web.BNS_ServiceReference.getPaymentRequestBody();
            inValue.Body.amount = amount;
            inValue.Body.cardNumber = cardNumber;
            inValue.Body.billID = billID;
            JPS_web.BNS_ServiceReference.getPaymentResponse retVal = ((JPS_web.BNS_ServiceReference.BNS_ServiceSoap)(this)).getPayment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JPS_web.BNS_ServiceReference.getPaymentResponse> JPS_web.BNS_ServiceReference.BNS_ServiceSoap.getPaymentAsync(JPS_web.BNS_ServiceReference.getPaymentRequest request) {
            return base.Channel.getPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<JPS_web.BNS_ServiceReference.getPaymentResponse> getPaymentAsync(float amount, long cardNumber, string billID) {
            JPS_web.BNS_ServiceReference.getPaymentRequest inValue = new JPS_web.BNS_ServiceReference.getPaymentRequest();
            inValue.Body = new JPS_web.BNS_ServiceReference.getPaymentRequestBody();
            inValue.Body.amount = amount;
            inValue.Body.cardNumber = cardNumber;
            inValue.Body.billID = billID;
            return ((JPS_web.BNS_ServiceReference.BNS_ServiceSoap)(this)).getPaymentAsync(inValue);
        }
    }
}
