//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPS_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int BillID { get; set; }
        public Nullable<System.DateTime> BillCreated { get; set; }
        public Nullable<System.DateTime> BillDue { get; set; }
        public Nullable<int> PremisesNumber { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string BillAddress { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
