//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNS_web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BNS_DBContainer : DbContext
    {
        public BNS_DBContainer()
            : base("name=BNS_DBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account2> Accounts { get; set; }
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<CardNumber> CardNumbers { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
    
        public virtual int cardInsert(Nullable<int> card)
        {
            var cardParameter = card.HasValue ?
                new ObjectParameter("card", card) :
                new ObjectParameter("card", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cardInsert", cardParameter);
        }
    }
}
