//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNS_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransID { get; set; }
        public string Date { get; set; }
        public string Type { get; set; }
        public string Details { get; set; }
        public string Amount { get; set; }
        public int AccountAccountNumber { get; set; }
    
        public virtual Account2 Account { get; set; }
    }
}
