//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPS_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int BillId { get; set; }
        public string Id { get; set; }
        public System.DateTime BillGenerationDate { get; set; }
        public System.DateTime BillDueDate { get; set; }
        public int PremisesNumber { get; set; }
        public int BillStatus { get; set; }
        public string Address { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
