<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="Dashboard.aspx.cs" Inherits="JPS_web.Account.Admin.Dashboard" %>

<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <%-- JS for search bar --%>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#SearchInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#TableDetails tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>



    <div class="container body-content">
        <h3>Manage Customer's Bill</h3>
        <div class="row">
            <div class="col-md-12 table-responsive">
                <asp:GridView ID="CustomerGridView" runat="server" AutoPostBack="True" CssClass="table table-bordered table-hover"
                    AutoGenerateColumns="False" DataKeyNames="BillId" DataSourceID="CustomerSqlDataSource" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" CellPadding="4" GridLines="None">
                    <Columns>
                        <asp:BoundField DataField="BillId" HeaderText="Bill Id" ReadOnly="true" InsertVisible="False" SortExpression="BillId"/>
                        <asp:BoundField DataField="Id" HeaderText="User Name" ReadOnly="true" SortExpression="Uname"/>
                        <asp:BoundField DataField="BillGenerationDate" HeaderText="Creation Date" ReadOnly="true" DataFormatString="{0:MM/dd/yyyy}" SortExpression="BillGenerationDate"/>
                        <asp:BoundField DataField="BillDueDate" HeaderText="Due Date" ReadOnly="true" DataFormatString="{0:MM/dd/yyyy}" SortExpression="BillDueDate"/>
                        <asp:BoundField DataField="PremisesNumber" HeaderText="Premises Number" SortExpression="PremisesNumber"/>
                        <asp:BoundField DataField="StatusName" ReadOnly="true" HeaderText="Bill Status" SortExpression="BillStatus"/>
                        <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address"/>
                        <asp:BoundField DataField="Amount" HeaderText="Amount" DataFormatString="{0:c}" SortExpression="Amount"/>
                    </Columns>
                </asp:GridView>
                <asp:SqlDataSource runat="server" ID="CustomerSqlDataSource" ConnectionString='<%$ ConnectionStrings:JPSContext %>' SelectCommand="SELECT Bills.BillId, Customers.UserName,Bills.Id, Bills.BillGenerationDate, Bills.BillDueDate, Bills.PremisesNumber, BillStatus.StatusName, Bills.Address, Bills.Amount FROM Bills INNER JOIN Customers ON Bills.Id = Customers.Id INNER JOIN BillStatus ON Bills.BillStatus = BillStatus.StatusID"
                    DeleteCommand="Delete from Bills WHERE BillId= @BillId;"
                    UpdateCommand="UPDATE [Bills] SET [Address] = @Address, [Amount] = @Amount, [PremisesNumber]= @PremisesNumber WHERE [Bills].[BillId] = @BillId">
                    <DeleteParameters>
                        <asp:Parameter Name="BillId"></asp:Parameter>
                    </DeleteParameters>
                </asp:SqlDataSource>
            </div>
        </div>
        <asp:HyperLink NavigateUrl="AddCustomerBill.aspx" Text="Add New Customer Bill" CssClass="btn btn-primary" runat="server" />

        <div class="row">
            <h3>Current Customers</h3>
            <input id="SearchInput" type="text" placeholder="Search for customers..">
            <br>
            <br>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>User Name</th>
                        <th>Full Name</th>
                        <th>Premises Number</th>
                    </tr>
                </thead>
                <tbody id="TableDetails">
                    <asp:Repeater ID="RepeaterDetails" runat="server">
                        <ItemTemplate>
                            <tr>
                                <td>
                                    <asp:Label ID="lbluname" runat="server" Text='<%#Eval("UserName") %>' />
                                </td>
                                <td>
                                    <asp:Label ID="lblfname" runat="server" Text='<%#Eval("FirstName") %>' />
                                    <asp:Label ID="lblname" runat="server" Text='<%#Eval("LastName") %>' />
                                </td>
                                <td>
                                    <asp:Label ID="lblpremnum" runat="server" Text='<%#Eval("PremisesNumber") %>' />
                                </td>
                        </ItemTemplate>
                    </asp:Repeater>
                </tbody>
            </table>
        </div>
    </div>
</asp:Content>
